# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{show_gem}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bj\303\270rn Arild M\303\246land"]
  s.date = %q{2009-12-23}
  s.description = %q{      Shows information about a gem, fetched from the Gemcutter site.
}
  s.email = %q{bjorn.maeland@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "History.txt",
     "README.rdoc",
     "Rakefile",
     "lib/rubygems/commands/show.rb",
     "lib/rubygems_plugin.rb",
     "test/test_helper.rb",
     "test/test_show_gem.rb"
  ]
  s.has_rdoc = false
  s.homepage = %q{http://github.com/bmaland/show_gem}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{showgem}
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Gem Command to easily display information about a ruby gem.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json_pure>, [">= 1.2.0"])
      s.add_runtime_dependency(%q<gemcutter>, [">= 0.2.1"])
    else
      s.add_dependency(%q<json_pure>, [">= 1.2.0"])
      s.add_dependency(%q<gemcutter>, [">= 0.2.1"])
    end
  else
    s.add_dependency(%q<json_pure>, [">= 1.2.0"])
    s.add_dependency(%q<gemcutter>, [">= 0.2.1"])
  end
end

